# Define qual application properties será carregado.
# OPTIONS: development | production
spring.profiles.active=production

application.name=Bem-vindo Marcos!

#server.port=8081
#server.servlet.context-path=/sistema-vendas
